services:
  database:
    container_name: zooshop-api-dev-database-container
    image: postgres:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: zooshop_api_dev
    volumes:
      - postgresql:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - zooshop-api-dev
    restart: unless-stopped
  email:
    container_name: zooshop-api-dev-email-container
    image: maildev/maildev:latest
    expose:
      - 1080
      - 1025
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  postgresql:
    driver: local

networks:
  zooshop-api-dev:
    driver: bridge
