spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  default-produces-media-type: application/json

server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    path: /error
    whitelabel:
      enabled: true