spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zooshop_api_dev
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  flyway:
    enabled: false
  sql:
    init:
      mode: never
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      write-dates-as-timestamps: false
    deserialization:
      fail-on-ignored-properties: false
  mail:
    host: localhost
    port: 1025
    username: dev
    password: dev
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    from: zooshop-noreply@zooshop.ru